src/controls/components/MultiChoiceOptions.tsx
src/controls/components/SingleChoiceOptions.tsx
src/generic/useClickOutside.tsx

1. In useClickOutside.tsx Added a reusable React hook to detect and handle clicks outside a specified element.
2. In SingleChoiceOptions.tsx and MultiChoiceOptions.tsx Integrated the new hook to automatically close the dropdown when clicking outside.
Before the changes:
After the changes:

UX: Automatically Close Dropdowns on Outside Click

---

src/controls/components/Selector.tsx
src/controls/components/TextInput.tsx
src/controls/controls.css
src/controls/selectors/LimitInput.tsx
src/controls/selectors/SearchBar.tsx
src/controls/selectors/useSearchSuggestions.tsx
src/views/common/ObjectTitle.tsx

This change improves the search suggestions interactions, in particular to support details view too. The user-journey we are focusing on here is that is someone starts a search, they may want to filter, but they may just want to jump straight to the details about what they are searching for.
So this refactors the suggestions box a bit and gives it the option to go to the Details view.
If you open the suggestions (here I entered Chinese to filter them) in most views, you'll see new button icons
| Before this PR | After this PR |
|--|--|
|<img width="352" alt="Screenshot 2025-05-20 at 12 21 14" src="https://github.com/user-attachments/assets/3bb863b4-8ec8-4c2b-85bb-aebc73bc504f" />|<img width="354" alt="Screenshot 2025-05-20 at 12 21 25" …

Search: Improve how search works with detailsSearch in details

---

src/dataloading/CensusData.tsx
src/dataloading/DataParsing.tsx
src/generic/numUtils.tsx
src/types/DataTypes.tsx
src/views/census/TableOfLanguagesInCensus.tsx
src/views/common/table/ObjectTable.tsx
src/views/locale/LocaleDetails.tsx

The census information is much better if you can actually see it in other places. While there are more places we need to plug it into, the first thing is to at least list it in the locale entries.
|Page|Before|After|
|--|--|--|
|[Canada Census details](https://translation-commons.github.io/lang-nav/?objectType=Census&view=Details&objectID=ca2021.1&limit=0)|<img width="771" alt="Screenshot 2025-06-03 at 14 34 39" src="https://github.com/user-attachments/assets/104cbf7e-d48e-4e43-b89b-7d7c6117e46f" />|<img width="772" alt="Screenshot 2025-06-03 at 14 34 24" src="https://github.com/user-attachments/assets/d80098a6-a9f1-4c3c-ad0a-f498b85411cb" />
|[French (Canada) details](https://translation-commons.github.io/lang-nav/?objectType=Locale&view=Details&objectID=fra_CA&limit=0)|<img width="509" …

Censuses: Show census records for locales

---

public/data/census/README.md
public/data/census/in2011c16.tsv
public/data/census/in2011c17.tsv
public/data/census/np2021.tsv
public/data/languages.tsv
src/data/CensusData.tsx
src/types/CensusTypes.tsx
src/views/census/CensusDetails.tsx

This change adds the 2021 Nepali census. Unfortunately, there are a number if language families (eg. Tharu, Tamang) and a number of uncoded dialects (mostly of Nepali but not always). Inferring individual Tharu/Tamang language estimates or adding partial dialects into better language estimates needs a bit more manual curation though so we will have to plan for that separately.
While I did this I also added 2 more good fields to the census metadata: collectorType and collectorName.
See the 4 new tables for Nepal. The live link for this view is https://translation-commons.github.io/lang-nav/?objectType=Census&view=Table

Censuses: Add Nepali census

---

src/generic/LinkButton.tsx
src/views/language/LanguageDetails.tsx

When researching about languages it's handy to follow these links and fortunately there is a structured way to get to the articles in both resources.
|Before|After|
|--|--|
|![Screenshot 2025-06-05 at 11 45 15](https://github.com/user-attachments/assets/86cc60c3-943a-4aa7-9281-ccb51750bad9)|![Screenshot 2025-06-05 at 11 37 46](https://github.com/user-attachments/assets/723fc0dc-0647-486c-87dc-9eae6c985c68)

Minor UX: Add links from languages to Wikipedia and Ethnologue

---

src/generic/PercentageDifference.tsx
src/generic/numberUtils.tsx
src/views/census/TableOfLanguagesInCensus.tsx
src/views/locale/LocaleCard.tsx
src/views/locale/LocaleDetails.tsx

This change adds a component that shows differences in percentages. It uses that new component to show the different of imported census data from the canonical locale population in the Census Details as well as the Locale Details.
|View|Before|After
|--|--|--
|[Locale Details for hi_IN](https://translation-commons.github.io/lang-nav/?objectType=Locale&view=Details&objectID=hin_IN&limit=0)|<img width="464" alt="Screenshot 2025-06-11 at 12 54 53" src="https://github.com/user-attachments/assets/895dbd8d-6c02-40f8-9c4a-4ba346666a94" />|<img width="542" alt="Screenshot 2025-06-11 at 12 54 58" src="https://github.com/user-attachments/assets/2de8bfda-feb5-4084-9e93-c801f25a38ad" />
|[Census Details for India 2011 L1](https://translation-commons.github.io/lang-nav/?objectType=Locale&view=Details&o …

Censuses: Add population difference

---

public/data/census/ca2021.tsv
src/views/common/HoverableObject.tsx
src/views/locale/LocaleCard.tsx
src/views/locale/LocaleCensusCitation.tsx
src/views/locale/LocaleDetails.tsx
src/views/locale/LocaleStrings.tsx
src/views/locale/LocaleTable.tsx

Now that we are starting to import files from the censuses, we can provide proper citations. This change improves the legibility of the citations and it also adds a HoverCard interaction so people can click to learn more about the census.
|What|Difference|Before|After|
|--|--|--|--|
|[Locale Cards](https://translation-commons.github.io/lang-nav/?objectType=Locale)|Citations shorted, and when it comes from a census there is now a way to hover over to get more details.|<img width="1319" alt="Screenshot 2025-06-17 at 15 25 13" src="https://github.com/user-attachments/assets/16b4be30-2570-4f5f-aac7-db5db864c9d8" />|<img width="1317" alt="Screenshot 2025-06-17 at 15 25 03" src="https://github.com/user-attachments/assets/58476c2d-7578-419a-8b59-cea84cb262e6" />
|[Locale …

Censuses: Add better citation when possible

---

src/data/CensusData.tsx
src/generic/stringUtils.tsx
src/views/census/TableOfLanguagesInCensus.tsx
src/views/common/HoverableObject.tsx
src/views/language/LanguageDetails.tsx

When importing census data, sometimes the census has slightly different names for languages. This adds those names to the languages' list of alternative names.
btw the edits to LanguageDetails.tsx are mostly a refactor -- breaking the large component into subcomponents. However I did change the othernames algorithm to actually use the names attribute (it wasn't yet, I had forgotten to do that).
|Example Locale|Before|After|
|--|--|--|
|[Bodo](https://translation-commons.github.io/lang-nav/?view=Details&objectID=brx&objectType=Language)|![Screenshot 2025-06-04 at 17 28 32](https://github.com/user-attachments/assets/1fbd4262-592a-4b6f-b230-7ab54fa974b2)|![Screenshot 2025-06-04 at 17 28 05](https://github.com/user-attachments/assets/ab5e576a-e698-47e1-883b-71ad776c1b75) …

Censuses: Add alternative language names from census imports

---

public/data/iso/families639-5.tsv
public/data/iso/familiesToLanguages.tsv
src/data/AddISOData.tsx
src/views/common/ObjectField.tsx
src/views/common/TreeList/TreeListNode.tsx
src/views/common/TreeList/TreeListOptions.tsx
src/views/common/TreeList/TreeListPageBody.tsx
src/views/common/TreeList/treelist.css

I'm preparing a report to IANA on oddities in language families and while I was collecting data I saw a few opportunities to fix the data and add visual display toggles.
Changes:
* Koreanic & Japonic languages removed from the disputed Altaic language family. Japonic ones moved to the `jpx` family
* Creoles and Pidgins that weren't grouped in the Creoles & Pidgins group are moved into it now
* Added 4 visual options for the hierarchy view. They are not tracked by page parameters since they are specific to that view. I'm happy to file other tasks to iterate on that.
|View|Before|After
|--|--|--
|[French languages](https://translation-commons.github.io/lang-nav/?view=Hierarchy&languageSchema=ISO&searchBy=English+Name&searchString=French)|<img width="385" alt="Screenshot 2025-06-06 at 16 10 …

Hierarchy: Add viewing options and update some language families

---

src/controls/selectors/ObjectTypeSelector.tsx

When a user switches between object types (e.g., from Census to Locale), we want to:
Clear any previous search filters (searchString: undefined)
Reset pagination to the first page (page: 1)

Update ObjectType Selector

---

src/views/census/TableOfAllCensuses.tsx
src/views/census/TableOfLanguagesInCensus.tsx
src/views/common/table/CommonColumns.tsx
src/views/common/table/ObjectTable.tsx
src/views/common/table/tableStyles.css
src/views/language/LanguageTable.tsx
src/views/locale/LocaleTable.tsx
src/views/territory/TerritoryTable.tsx
src/views/writingsystem/WritingSystemTable.tsx

This pull request implements the column filtering feature for the `ObjectTable` component, resolving Issue [#91](https://github.com/Translation-Commons/lang-nav/issues/91).
**Changes made:**
- Updated the `TableColumn` interface in `ObjectTable.tsx` to require a unique `key` property.
- Added state management within `ObjectTable.tsx` to track and toggle column visibility.
- Added a checkbox UI to allow users to control which columns are shown.
- Updated all existing tables (`Languages`, `Censuses`, etc.) to provide the required `key` for each column definition.
Fixes #91

Added column filtering for tables #91

---

public/data/census/README.md
public/data/census/es2021.tsv
src/data/CensusData.tsx
src/types/CensusTypes.tsx
src/types/LanguageTypes.tsx
src/views/common/table/tableStyles.css

This change adds the census data from the 2021 Spanish census. The website is in Spanish but I could read it and I was very happy by all of the breakdowns available. I got a bit carried away adding various different slides of the data.
While I added the various interpretations I also added more enum values for `LanguageModality` to compliment what we get in the census, added the ability to suppress language name rows using a `#` symbol if the row is just there for context, added sticky headers to the object table.
|What|Before|After|
|--|--|--|
|[Censuses table](https://translation-commons.github.io/lang-nav/?objectType=Census&view=Table) lots of new census records (scrolled down to see them since they only have a handful of langauges)|<img width="517" alt="Screenshot 2025-06-27 at 08 39 …

Census: Add Spain census data (#88)

---

src/data/DataParsing.tsx
src/data/IANAData.tsx
src/data/PopulationData.tsx
src/types/DataTypes.tsx
src/types/ScopeLevel.tsx
src/views/ViewReports.tsx
src/views/common/table/ObjectTable.tsx
src/views/common/table/tableStyles.css
src/views/language/DubiousLanguages.tsx
src/views/language/LanguagesWithIdenticalNames.tsx
src/views/locale/PotentialLocales.tsx
src/views/styles.css

This adds a report that shows locales derived from census data that seem like they should be added to the enumerated list of locales.
~~I'll note that of the indigenous languages listed -- most are macrolanguages or are just missing data. Hazaragi is a dialect of Dari (Persian) that would be biggest in Afghanistan. Funny enough, none in the screenshot seem to be good ideas -- but if you scroll down the list or change % thresholds you see better ones. For example, Tippera [tpe] should be listed a locale in India.~~ Resolved! I updated the algorithm
Link: https://translation-commons.github.io/lang-nav/?objectType=Locale&view=Reports
With the other options expanded

Censuses: Show potential locales

---

src/views/VisibleItemsMeter.tsx
src/views/common/CardList.tsx
src/views/common/table/ObjectTable.tsx
src/views/language/LanguageTable.tsx
src/views/styles.css

This change refactors the VisibleItemsMeter, simplifying the code and improving the communication about what is filtered out. Now it has 3 discrete sections: "Showing X of Y results", "Z filtered out", "On Page < W > of V". If you hover of the filtered out section it provides a bit more context -- I'd like to add more but right now I'm working on refactoring the code that will appear there so I think its better to start with this and incrementally update.
|Before|After|
|--|--|
And see here how what it looks like

Filters: Show why there are hidden entries.

---

src/data/CensusData.tsx
src/data/PopulationData.tsx
src/data/SupplementalData.tsx
src/data/UnicodeData.tsx
src/types/CensusTypes.tsx
src/views/locale/LocaleCensusCitation.tsx
src/views/locale/PotentialLocales.tsx

CLDR population estimates are available in the CLDR json package. This imports those estimates and ranks them lower than the actual censuses. CLDR has data for every country, we get a lot more values. It will be better to get census and other sources but this helps fill in missing values.
|Page|Changes|Before|After|
|--|--|--|--|
|[Locale Table](https://translation-commons.github.io/lang-nav/?objectType=Locale&view=Table)|You see a number of entries now have a new population source -- CLDR (underlined) -- which you can hover over to get more information about the source. It doesn't replace the actual census values (since CLDR is ranked lower in accuracy). The population numbers are updated and sorted slightly differently now too. Urdu and Panjabi (Pakistan) jumped up, others increased and …

Census: Import "CLDR" population estimates

---

src/App.tsx
src/controls/PageNavBar.tsx
src/controls/SidePanel.tsx
src/controls/controls.css
src/index.css
src/views/common/CardList.tsx
src/views/styles.css

This moves the controls that you can toggle to view or hide to a toggleable sidebar.
I'd love to get design feedback. Just note I don't update the selectors in this change because I realized I needed a more thorough refactor because the CSS styles have become too complex.
While I was here I also moved some styles from .css files to be inline instead. After working on this program for awhile I realized I was adding some modern anti-patterns. If you put too many styles in CSS files then it can be harder to understand. Inline styles muck up files, but you can improve this by adding Container/Body/Header... components inside the file.
Also note I did a quick refactor of the CardList component as well because I noticed it was responsive to the whole window width, rather than the container …

UX: Move controls to sidepanel

---

src/App.tsx
src/controls/PageParamsContext.tsx
src/controls/SidePanel.tsx
src/controls/components/Selector.tsx
src/controls/components/SelectorLabel.tsx
src/controls/components/TextInput.tsx
src/controls/controls.css
src/controls/filter.tsx
src/controls/selectors/LanguageScopeSelector.tsx
src/controls/selectors/LimitInput.tsx
src/controls/selectors/SearchBar.tsx
src/controls/selectors/TerritoryFilter.tsx
src/controls/selectors/TerritoryScopeSelector.tsx
src/controls/selectors/ViewSelector.tsx
src/controls/selectors/useSearchSuggestions.tsx
src/data/DataContext.tsx
src/generic/HoverableButton.tsx
src/types/PageParamTypes.tsx
src/views/Loading.tsx
src/views/PageBody.tsx
src/views/PageContents.tsx
src/views/VisibleItemsMeter.tsx
src/views/common/CardList.tsx
src/views/common/ObjectField.tsx
src/views/common/TreeList/TreeListPageBody.tsx
src/views/common/table/ObjectTable.tsx
src/views/language/DubiousLanguages.tsx
src/views/language/LanguagesWithIdenticalNames.tsx
src/views/locale/PotentialLocales.tsx

The search bar had a "territory" option but imho that was overloading the search bar since it was hard to discover.
Now you can use the territory filter separately! While I was here I also changed lazy loading to break up the JS filesize and I improved the rendering of text-input controls in the sidepanel.
|Before|After|
|--|--|
|<img width="1416" height="830" alt="Screenshot 2025-07-25 at 20 16 41" src="https://github.com/user-attachments/assets/422cc882-f470-4dce-be39-7eb522ff2b84" />|<img width="1423" height="828" alt="Screenshot 2025-07-25 at 20 17 17" src="https://github.com/user-attachments/assets/1c675b21-ff15-4a5e-9892-ae90f0fdcde8" />

Controls: Separate Territory Filter control

---

public/data/census/data.un.org/bs.tsv
public/data/census/yt.tsv
public/data/locales.tsv
src/data/CensusData.tsx
src/types/CensusTypes.tsx

This adds data from the Mayotte and Bahamas censuses.
While I was here I also added the ability to suppress a census table during import -- this way we can include raw data without adding extraneous data.
See the new Mayotte locales here:
https://translation-commons.github.io//lang-nav/data?territoryFilter=yt&languageScopes=Macrolanguage%2CLanguage%2CDialect&view=Table&objectType=Locale
|Before|After|
|--|--|
|<img width="619" height="152" alt="Screenshot 2025-07-29 at 17 32 30" src="https://github.com/user-attachments/assets/ba73574b-2447-4f2d-92a7-bc3ef6e9f06e" />|<img width="629" height="296" alt="Screenshot 2025-07-29 at 17 32 09" src="https://github.com/user-attachments/assets/7b84fb9f-8e28-4921-8f57-3d127cea558e" />

Data: Mayotte and Bahamas Census

---

src/controls/selectors/SortBySelector.tsx
src/controls/sort.tsx
src/data/PopulationData.tsx
src/generic/CommaSeparated.tsx
src/generic/Hoverable.tsx
src/generic/HoverableEnumeration.tsx
src/generic/numberUtils.tsx
src/generic/styles.css
src/types/DataTypes.tsx
src/types/PageParamTypes.tsx
src/views/census/TableOfAllCensuses.tsx
src/views/common/table/CommonColumns.tsx
src/views/common/table/ObjectTable.tsx
src/views/language/LanguageTable.tsx
src/views/locale/LocaleTable.tsx
src/views/territory/TerritoryTable.tsx
src/views/writingsystem/WritingSystemTable.tsx

This change adds a lot more sorting options and table columns to show then.
Changes
* Add new sorting options
* Endonym
* Percent (%)
* Count of Languages (#L)
* Count of Territories (#T)
* New table columns
* **Languages**: Endonyms, Dialects (#L)
* **Locales**: Endonyms, % in Territory, Contained Locales (#L)
* **Censuses**: <i>no change</i>
* **Territories**: Only change is that the Literacy (%) & Languages (#L) columns are sortable
* **Writing Systems**: Endonyms
* `isInitiallyVisible` option to table view to mitigate having so many new columns.
Not everything is final yet -- posting for feedback.

Sorting: Add more sort options

---

src/views/common/CLDRCoverageInfo.tsx
src/views/language/LanguageDetails.tsx
src/views/language/LanguageTable.tsx

This pull request resolves issue #119 by splitting the "Internet Technologies" column into two separate, more specific columns: "CLDR Coverage" and "ICU Support."
-   **Refactored `CLDRCoverageInfo.tsx`:** Broke down the original component `CLDRCoverageInfo` into two new, reusable components:
-   `CLDRCoverageText`: Renders only the CLDR information.
-   `ICUSupportStatus`: Renders only the ICU support status icon.
-   **Updated `LanguageTable.tsx`:** Replaced the single "Internet Technologies" column with the two new, more focused columns, each using one of the new components.
-   **Updated `LanguageDetails.tsx`:** Aligned the language details page with the new table structure by displaying "CLDR Coverage" and "ICU Support" as separate fields.
|Link|Before|After|
|--|--|--| …

Table: Split 'Internet Technologies' column into two.

---

src/controls/components/MultiChoiceOptions.tsx
src/controls/components/Selector.tsx
src/controls/components/SelectorLabel.tsx
src/controls/components/SingleChoiceOptions.tsx
src/controls/components/TextInput.tsx
src/controls/controls.css
src/controls/pathnav/PathNav.tsx
src/controls/selectors/ObjectTypeSelector.tsx
src/controls/selectors/PaginationControls.tsx
src/controls/selectors/SearchBar.tsx
src/generic/PositionInGroup.tsx
src/pages/DataPage.tsx
src/views/DataPageBody.tsx
src/views/styles.css

One of the biggest pieces of feedback from recent user interviews was difficult navigating to the right page. A design that I considered was breadcrumbs and after playing around with it I really like how it looks.
This PR starts the concept with the 2 main selectors. While adding the inline-dropdown selector style, I revamped other parts of selector style to abide by some better front-end practices (in particular, I'm now leaning to the school of thought to have inline Styles rather than separate CSS files).
See the new buttons
Finishes #149

Navigation: Add initial path breadcrumbs component & add inline-dropdown selector style

---

src/types/CensusTypes.tsx
src/views/ViewReports.tsx
src/views/census/TableOfCountriesWithCensuses.tsx
src/views/common/CollapsibleReport.tsx
src/views/language/DubiousLanguages.tsx
src/views/language/LanguagesWithIdenticalNames.tsx
src/views/locale/PotentialLocales.tsx

This PR adds a report so that we can see how many census sources we have available for each country so we can track which countries are in need of census data.
https://translation-commons.github.io/lang-nav/data?view=Reports&objectType=Census&sortBy=Count+of+Languages

Reports: List census progress

---

src/controls/components/Selector.tsx
src/controls/components/SelectorDisplay.tsx
src/controls/components/SelectorLabel.tsx
src/controls/components/SelectorOption.tsx
src/controls/components/TextInput.tsx
src/controls/pathnav/FilterPath.tsx
src/controls/pathnav/ObjectPathChildren.tsx
src/controls/pathnav/PathNav.tsx
src/controls/selectors/LanguageSourceSelector.tsx
src/controls/selectors/LimitInput.tsx
src/controls/selectors/LocaleSeparatorSelector.tsx
src/controls/selectors/ProfileSelector.tsx
src/controls/selectors/SearchBar.tsx
src/controls/selectors/SearchBySelector.tsx
src/controls/selectors/SortBySelector.tsx
src/controls/selectors/SortDirectionSelector.tsx
src/controls/selectors/TerritoryFilterSelector.tsx
src/generic/setUtils.tsx
src/views/locale/PotentialLocaleThreshold.tsx

This change extends the path description at the top of the page to include the active filters. See the new information below the search bar.
While I was here I also moved some more elements out of Selector.tsx into their own files.
https://translation-commons.github.io/lang-nav/data?languageScopes=Family%2CMacrolanguage%2CLanguage&territoryFilter=Ira&territoryScopes=Country%2CDependency%2CSub-continent&view=Hierarchy&objectType=Locale&searchString=kurd

Add filters to page path

---

src/controls/selectors/TerritoryScopeSelector.tsx
src/pages/CommonObjectives.tsx
src/views/VisibleItemsMeter.tsx
src/views/census/TableOfLanguagesInCensus.tsx
src/views/common/table/ObjectTable.tsx

Some improvements to search so it reduces conflicts. In particular, you may search for a particular census by name but then when you open up the details on the census it shows 0 results in the language table. Since that table works on a different kind of object, we shouldn't use the page search on it.
This change also adds the territory scope filter when in census reports since that filter can be used.
|Before|After|
|--|--|
|<img width="784" height="578" alt="Screenshot 2025-08-19 at 18 59 44" src="https://github.com/user-attachments/assets/98bb3595-72a7-479d-a1b0-529da88d7371" />|<img width="781" height="644" alt="Screenshot 2025-08-19 at 18 59 37" src="https://github.com/user-attachments/assets/48e66fed-781a-4512-a8c9-9c33ceed6df4" />

Search: Misc improvements with Census languages

---

public/data/locales.tsv
public/data/wikipedias.tsv
src/data/IANAData.tsx
src/data/SupplementalData.tsx
src/data/WikipediaData.tsx
src/generic/LinkButton.tsx
src/types/DataTypes.tsx
src/types/LanguageTypes.tsx
src/views/common/ObjectWikipediaInfo.tsx
src/views/language/LanguageDetails.tsx
src/views/language/LanguageDetailsVitalityAndViability.tsx
src/views/language/LanguageTable.tsx
src/views/locale/LocaleDetails.tsx
src/views/locale/LocaleTable.tsx

This PR adds Wikipedia information to languages & locales in the Details view and the Table view.
|View|Explanation|Screenshot|
|--|--|--|
|[Chinese Vitality](http://localhost:5173/lang-nav/data?objectID=zho&view=Details)|There's a new row showing the wikipedia information.|<img width="832" height="238" alt="Screenshot 2025-09-17 at 10 57 07" src="https://github.com/user-attachments/assets/d3810e51-0b90-4444-8327-e9e0977913ec" />
|[Language table](http://localhost:5173/lang-nav/data?view=Table&limit=13&page=11)|There is a new column (defaults to hidden) that shows wikipedia data. I scrolled to a few pages in so you could see some languages in different states of wikipedia development. You'll notice its a bit more abridged to fit in a smaller space.|<img width="682" height="548" …

Data: Add wikipedia availability

---

src/controls/pathnav/getParentsAndDescendents.tsx
src/controls/sort.tsx
src/data/CensusData.tsx
src/data/DataAssociations.tsx
src/data/DataParsing.tsx
src/data/PopulationData.tsx
src/data/TerritoryData.tsx
src/types/DataTypes.tsx
src/views/census/CensusHierarchy.tsx
src/views/census/TableOfCountriesWithCensuses.tsx
src/views/common/ObjectField.tsx
src/views/locale/LocaleDetails.tsx
src/views/locale/LocaleHierarchy.tsx
src/views/locale/PotentialLocales.tsx
src/views/territory/TerritoryCard.tsx
src/views/territory/TerritoryDetails.tsx
src/views/territory/TerritoryHierarchy.tsx
src/views/territory/TerritoryTable.tsx
src/views/writingsystem/WritingSystemCard.tsx
src/views/writingsystem/WritingSystemDetails.tsx
src/views/writingsystem/WritingSystemHierarchy.tsx
src/views/writingsystem/WritingSystemTable.tsx

In a separate branch I am adding unit tests but I noticed the code to mock objects is pretty big because of the amount of fields. Fortunately we can set most of those fields to be optional and save us needing to declare so many.
Tested by `npm run build` and also using the website to make sure it still works fine.

Refactor: Make more optional fields for objects

---

src/views/language/LanguageCard.tsx
src/views/language/LanguageDetailsVitalityAndViability.tsx
src/views/language/LanguageVitalityComputation.tsx
src/views/language/LanguageVitalityMeter.tsx

Implements the **Vitality Metascore** system to reconcile ISO, Ethnologue 2013, and Ethnologue 2025 vitality measures.
- **`LanguageVitalityComputation.tsx`**
- `getEthnologue2013Score()`: maps values to 0–9 scale  
- `getEthnologue2025Score()`: maps values to 0–9 scale (Institutional=9, Stable=6, Endangered=3, Extinct=0)  
- `getISOScore()`: maps ISO values to 0–9 scale (Living=9, Constructed=3, Historical=1, Extinct=0)  
- `computeVitalityMetascore()`:  
- If both Ethnologue values exist → average  
- If only one exists → use that  
- If none exist → fallback to ISO scale  
- `getAllVitalityScores()`: returns all vitality scores for display  
- **`LanguageVitalityMeter.tsx`**
- Accepts a `LanguageData` object  
- Uses the metascore computation  
- Shows hover explanation with …

feat: implement vitality metascore calculation and integrate (#213)

---

src/data/DataParsing.tsx
src/views/common/HoverableObject.tsx
src/views/common/table/CommonColumns.tsx
src/views/common/table/ObjectTable.tsx
src/views/common/table/TableColumnSelector.tsx
src/views/language/LanguageTable.tsx
src/views/locale/LocaleTable.tsx

This change adds column groups. Since we're adding more and more data it gets hard to maintain. Fortunately we can group columns.
|What|Before|After|
|--|--|--|
|[Language Table](https://translation-commons.github.io/lang-nav/data?view=Table&languageScopes=Macrolanguage%2CLanguage&objectType=Language)|<img width="748" height="371" alt="Screenshot 2025-10-02 at 10 56 46" src="https://github.com/user-attachments/assets/ae4193d7-2c2c-40d6-afe7-0d8f313b40ff" />|<img width="747" height="428" alt="Screenshot 2025-10-02 at 10 53 28" src="https://github.com/user-attachments/assets/490f423c-c22a-44e4-9cfc-bf548b42d7b3" />
|[Locale Table](https://translation-commons.github.io/lang-nav/data?view=Table&languageScopes=Macrolanguage%2CLanguage&objectType=Locale)|<img width="748" height="341" …

Table: Add column groups
